name: dentistry
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  overlay_support: ^1.2.1
  flutter_local_notifications: ^9.0.1
  flutter_bloc: ^8.0.0
  retrofit: ^2.1.0
  logger: ^1.1.0
  dio: ^4.0.1
  equatable: ^2.0.0
  hydrated_bloc: ^8.0.0
  bloc: ^8.0.1
  json_serializable: ^6.0.1
  json_annotation: ^4.4.0
  path_provider: ^2.0.7
  firebase_auth: ^3.1.4
  firebase_dynamic_links: ^2.0.11
  firebase_messaging: ^11.2.6
  firebase_core: ^1.7.0
  firebase_database: ^9.0.4
  flutter_svg: ^1.0.0
  bottom_navy_bar: ^6.0.0
  customizable_space_bar: ^0.2.0
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0
  solid_bottom_sheet: ^0.1.10
  flutter_advanced_drawer: ^1.3.0
  shared_preferences: ^2.0.11
  package_info_plus: ^1.3.0
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  firebase_storage: ^10.2.6
  cloud_firestore: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^2.1.0+1
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
